/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHead: typeof import('./inertia/components/AppHead.vue')['default']
    Button: typeof import('./inertia/components/ui/button/Button.vue')['default']
  }
}
