/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHead: typeof import('./inertia/components/AppHead.vue')['default']
    Button: typeof import('./inertia/components/ui/button/Button.vue')['default']
    DropdownMenu: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuCheckboxItem: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    DropdownMenuContent: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuGroup: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    DropdownMenuItem: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuRadioGroup: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    DropdownMenuRadioItem: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    DropdownMenuSeparator: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuShortcut: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    DropdownMenuSub: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    DropdownMenuSubContent: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    DropdownMenuSubTrigger: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    DropdownMenuTrigger: typeof import('./inertia/components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    FormInput: typeof import('./inertia/components/FormInput.vue')['default']
    Input: typeof import('./inertia/components/ui/input/Input.vue')['default']
    Label: typeof import('./inertia/components/ui/label/Label.vue')['default']
    Navigation: typeof import('./inertia/components/Navigation.vue')['default']
    Sheet: typeof import('./inertia/components/ui/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./inertia/components/ui/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./inertia/components/ui/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./inertia/components/ui/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./inertia/components/ui/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./inertia/components/ui/sheet/SheetHeader.vue')['default']
    SheetTitle: typeof import('./inertia/components/ui/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./inertia/components/ui/sheet/SheetTrigger.vue')['default']
  }
}
